/* Generated by Yosys 0.19+36 (git sha1 a207fd4b335, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module pes_3bit_rc(clk, ori, count);
  wire _0_;
  input clk;
  wire clk;
  output [2:0] count;
  wire [2:0] count;
  input ori;
  wire ori;
  wire [2:0] temp;
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(ori),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(temp[1]),
    .Q(temp[0]),
    .RESET_B(_0_)
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(temp[2]),
    .Q(temp[1]),
    .RESET_B(_0_)
  );
  sky130_fd_sc_hd__dfstp_2 _4_ (
    .CLK(clk),
    .D(temp[0]),
    .Q(temp[2]),
    .SET_B(_0_)
  );
  assign count = temp;
endmodule
